#!/bin/sh

set -e

# shellcheck disable=SC2039
source setup-helpers

echo "Generating an RSA token for GitHub"
mkdir -p ~/.ssh
touch ~/.ssh/config
ssh-keygen -t rsa -b 4096 -C "iamfotx@gmail.com"
echo "Host *\n AddKeysToAgent yes\n UseKeychain yes\n IdentityFile ~/.ssh/id_rsa" | tee ~/.ssh/config
eval "$(ssh-agent -s)"
pbcopy < ~/.ssh/id_rsa.pub
echo "RSA token has been copied to clipboard, paste that into GitHub"


# Install git
# TODO: Make this cross-platform
brew install git

install_dotfile "gitignore"

git config --global alias.br branch
git config --global alias.cm commit
git config --global alias.cmm "commit -m"
git config --global alias.co checkout
git config --global alias.lol "log --graph --decorate --pretty=oneline --abbrev-commit"
git config --global alias.lola "log --graph --decorate --pretty=oneline --abbrev-commit --all"
git config --global alias.ls ls-files
git config --global alias.st status

git config --global color.ui true

git config --global core.autocrlf input
git config --global core.editor vim
git config --global core.eol lf
git config --global core.excludesfile "$HOME/.gitignore"

git config --global credential.helper osxkeychain

git config --global push.default current

git config --global url.https://.insteadOf git://

git config --global user.email "iamfotx@gmail.com"
git config --global user.name "iamfotx"
