#!/bin/sh

set -e

# Install nvm
curl -o- https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash

# Install and use node version 10 by default
nvm install 12
nvm alias default 12

# Install yarn
curl -o- -L https://yarnpkg.com/install.sh | bash

# Install a few packages globally
yarn global add create-react-app prettier serve
