#!/bin/sh

set -e

homebrew_prefix="/usr/local"

if [ -d "$homebrew_prefix" ]; then
  if ! [ -r "$homebrew_prefix" ]; then
    sudo chown -R "$LOGNAME:admin" /usr/local
  fi
else
  sudo mkdir "$homebrew_prefix"
  sudo chflags norestricted "$homebrew_prefix"
  sudo chown -R "$LOGNAME:admin" "$homebrew_prefix"
fi

if ! command -v brew >/dev/null; then
  curl -fsS \
    'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby
fi

brew update

echo "brew installing stuff"
# hub: a github-specific version of git
# ripgrep: rg is faster than alternatives
# imagemagick: eventually I will need this for something
# ffmpeg: eventually I'll need this for something
# tree: really handy for listing out directories in text
# bat: A cat(1) clone with syntax highlighting and Git integration.
# switchaudio-osx: allows me to switch the audio device via the command line
brew install hub ripgrep imagemagick watchman tree bat \
delta switchaudio-osx
